version: '3.0'

services:
  backend:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      - '7979:7979'
    networks:
      - urlnet
    volumes:
      - ./server:/app/
      - type: bind
        source: ./server/jest-reports
        target: /usr/src/app/jest-reports
    depends_on:
      - redis
    environment:
      REST_PORT: $REST_PORT
      SOCKET_PORT: $SOCKET_PORT
      GEN_TEST_REPORTS: $GEN_TEST_REPORTS
      JWT_KEY: $JWT_KEY
      REDIS_URL: $REDIS_URL
      CORS_ORIGINS: $CORS_ORIGINS
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    networks:
      - urlnet
  redoc:
    image: redocly/redoc
    environment:
      SPEC_URL: $OPEN_API_SPEC
      PORT: 8081
      PAGE_TITLE: Farm IDLE – API Docs
    networks:
      - urlnet
    ports:
      - '8081:8081'
    depends_on:
      - backend
  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    networks:
      - urlnet

networks:
  urlnet:
  