version: '3.0'

services:
  backend:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      - '7979:7979'
    networks:
      - urlnet
    volumes:
      - ./server:/app/
      - type: bind
        source: ./server/jest-reports
        target: /usr/src/app/jest-reports

    environment:
      REST_PORT: $REST_PORT
      SOCKET_PORT: $SOCKET_PORT
      GEN_TEST_REPORTS: $GEN_TEST_REPORTS
      JWT_KEY: $JWT_KEY
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - urlnet

networks:
  urlnet:
  